version: "3.9"
services:
  backend-a:
    build: ./backend-a

  backend-b:
    build: ./backend-b

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - backend-a
      - backend-b
      - redis
    environment:
      - REDIS_HOST=redis
